package traceability;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static traceability.TraceStart.stammdaten;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author U14
 */
public class TraceTHTMaterialKopieren extends javax.swing.JFrame {
    
    private MaterialDAO materialDAO;
    private MaterialDAO insertMaterialDAO;
    
    private JTable tableVon;
    private JTable tableNach;

    /**
     * Creates new form Trace
     */
    public TraceTHTMaterialKopieren() {
        initComponents();
        
          try {
            materialDAO = new MaterialDAO();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(TraceTHTMaterialKopieren.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldBetriebsauftrag = new javax.swing.JTextField();
        jLabelTischNr = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jTextFieldMaschine = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        jTextFieldMaschine1 = new javax.swing.JTextField();
        jScrollPaneMaterialNach = new javax.swing.JScrollPane();
        jScrollPaneMaterialVon = new javax.swing.JScrollPane();
        jButtonAnzeigeVonMaterial = new javax.swing.JButton();

        setTitle("Tracebility THT Material");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(320, 400));
        setMaximumSize(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THT Material kopieren");

        jTextFieldBetriebsauftrag.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldBetriebsauftrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBetriebsauftragActionPerformed(evt);
            }
        });

        jLabelTischNr.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("Von Arbeitsplatz ");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Betriebsauftrag:");

        jTextFieldMaschine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldMaschine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaschineActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("nach Arbeitsplatz ");

        jTextFieldMaschine1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldMaschine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaschine1ActionPerformed(evt);
            }
        });

        jButtonAnzeigeVonMaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAnzeigeVonMaterial.setText("Anzeigen");
        jButtonAnzeigeVonMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnzeigeVonMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTischNr)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldMaschine, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBetriebsauftrag, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaschine1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnzeigeVonMaterial))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneMaterialNach, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneMaterialVon)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTischNr)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBetriebsauftrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaschine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldMaschine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAnzeigeVonMaterial)))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPaneMaterialVon, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMaterialNach, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        label7.getAccessibleContext().setAccessibleName("nach Arbeitsplatz ");
        tableNach = new JTable();
        jScrollPaneMaterialNach.setViewportView(tableNach);
        tableVon = new JTable();
        jScrollPaneMaterialVon.setViewportView(tableVon);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBetriebsauftragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBetriebsauftragActionPerformed
        // TODO add your handling code here:
        //jTextFieldPmNr.setEnabled(false);
        //labelBetriebsauftrag.setBounds(10, 100, 100, 10);
        jTextFieldBetriebsauftrag.setEditable(false);
        jTextFieldMaschine.requestFocus();
        //labelBetriebsauftrag.setVisible(true);
        //labelBetriebsauftrag.setText(jTextFieldPmNr.getText());
    }//GEN-LAST:event_jTextFieldBetriebsauftragActionPerformed

    private void jTextFieldMaschineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaschineActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextFieldMaschineActionPerformed

    private void jTextFieldMaschine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaschine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaschine1ActionPerformed

    private void jButtonAnzeigeVonMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnzeigeVonMaterialActionPerformed
        // TODO add your handling code here:
        
        String betriebsauftrag = jTextFieldBetriebsauftrag.getText();
        
        List<Material> material = null;
        
         try {
            material = materialDAO.getMaterial(betriebsauftrag, stammdaten.getArbeitsplatz());
        } catch (SQLException ex) {
            Logger.getLogger(TraceThtMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MaterialTableModel model;
        model = new MaterialTableModel(material);
        tableVon.setModel(model);
        
        // Tabelle nach der 2. Spalte sortiet
        tableVon.setAutoCreateRowSorter(true);
        tableVon.getRowSorter().toggleSortOrder(1);
        tableVon.getRowSorter().toggleSortOrder(1);
    }//GEN-LAST:event_jButtonAnzeigeVonMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraceTHTMaterialKopieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraceTHTMaterialKopieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraceTHTMaterialKopieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraceTHTMaterialKopieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraceTHTMaterialKopieren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnzeigeVonMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTischNr;
    private javax.swing.JScrollPane jScrollPaneMaterialNach;
    private javax.swing.JScrollPane jScrollPaneMaterialVon;
    private javax.swing.JTextField jTextFieldBetriebsauftrag;
    private javax.swing.JTextField jTextFieldMaschine;
    private javax.swing.JTextField jTextFieldMaschine1;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
