package traceability;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author U14
 */
public class Trace extends javax.swing.JFrame {
    
    private MaterialDAO materialDAO;
    private JTable table;

    /**
     * Creates new form Trace
     */
    public Trace() {
        initComponents();
        
        try {
            materialDAO = new MaterialDAO();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Trace.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCharge = new javax.swing.JTextField();
        jTextFieldSeriennummer = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label3 = new java.awt.Label();
        jTextFieldPmNr = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label4 = new java.awt.Label();
        jTextFieldKuerzel = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        jTextFieldTischNr = new javax.swing.JTextField();
        jButtonNeu = new javax.swing.JButton();
        jButtonTestkonsolenausgabe = new javax.swing.JButton();
        jScrollPaneMaterial = new javax.swing.JScrollPane();
        jLabelTischNr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tracebility THT Material");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 400));
        setResizable(false);

        jTextFieldCharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChargeActionPerformed(evt);
            }
        });

        jTextFieldSeriennummer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSeriennummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeriennummerActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Seriennummer:");

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Kürzel:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Traceability THT Material");

        jSeparator1.setName("TracebilityThtMaterial"); // NOI18N

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("PM-Nr:");

        jTextFieldPmNr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPmNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPmNrActionPerformed(evt);
            }
        });

        jSeparator2.setName("TracebilityThtMaterial"); // NOI18N

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Charge:");

        jTextFieldKuerzel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldKuerzel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKuerzelActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("Tisch-Nr:");

        jTextFieldTischNr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTischNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTischNrActionPerformed(evt);
            }
        });

        jButtonNeu.setBackground(new java.awt.Color(255, 51, 255));
        jButtonNeu.setText("Neu");
        jButtonNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeuActionPerformed(evt);
            }
        });

        jButtonTestkonsolenausgabe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTestkonsolenausgabe.setForeground(new java.awt.Color(0, 51, 153));
        jButtonTestkonsolenausgabe.setText("Testkonsolenausgabe");
        jButtonTestkonsolenausgabe.setToolTipText("Hier wird die komplette Tabelle Matrial Testweise in die Konsole ausgegeben");
        jButtonTestkonsolenausgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestkonsolenausgabeActionPerformed(evt);
            }
        });

        jLabelTischNr.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldSeriennummer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldKuerzel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPmNr, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTischNr, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneMaterial)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonTestkonsolenausgabe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNeu)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTischNr)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTischNr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKuerzel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTischNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPmNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSeriennummer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPaneMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNeu)
                    .addComponent(jButtonTestkonsolenausgabe))
                .addContainerGap())
        );

        jButtonTestkonsolenausgabe.getAccessibleContext().setAccessibleDescription("Hier wird die komplette Tabelle Matrial Testweise in die Konsole ausgegeben");
        table = new JTable();
        jScrollPaneMaterial.setViewportView(table);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChargeActionPerformed
        // TODO add your handling code here:
        //System.out.println("Charge:  " + jTextFieldCharge.getText());
        //charge.setText("");
        jTextFieldSeriennummer.requestFocus();
    }//GEN-LAST:event_jTextFieldChargeActionPerformed

    private void jTextFieldSeriennummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeriennummerActionPerformed
        // TODO add your handling code here:
        System.out.println("Kuezel: " + jTextFieldKuerzel.getText() + 
                           " PmNr: " + jTextFieldPmNr.getText() + 
                            " Tisch: " + jTextFieldTischNr.getText() + 
                            " Charge: " + jTextFieldCharge.getText() + 
                            " Seriennummer: " + jTextFieldSeriennummer.getText());
        
        jTextFieldSeriennummer.setText("");
        jTextFieldCharge.setText("");
        jTextFieldCharge.requestFocus();
        
    }//GEN-LAST:event_jTextFieldSeriennummerActionPerformed

    private void jTextFieldPmNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPmNrActionPerformed
        // TODO add your handling code here:
        jTextFieldTischNr.requestFocus();
    }//GEN-LAST:event_jTextFieldPmNrActionPerformed

    private void jTextFieldKuerzelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKuerzelActionPerformed
        // TODO add your handling code here:
        jTextFieldPmNr.requestFocus();
    }//GEN-LAST:event_jTextFieldKuerzelActionPerformed

    private void jTextFieldTischNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTischNrActionPerformed
        // TODO add your handling code here:
        jTextFieldCharge.requestFocus();
        jTextFieldKuerzel.setEnabled(false);
        jTextFieldPmNr.setEnabled(false);
        jTextFieldTischNr.setEnabled(false);
        jLabelTischNr.setText(jTextFieldTischNr.getText());
    }//GEN-LAST:event_jTextFieldTischNrActionPerformed

    private void jButtonNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeuActionPerformed
        // TODO add your handling code here:
        jTextFieldKuerzel.setEnabled(true);
        jTextFieldPmNr.setEnabled(true);
        jTextFieldTischNr.setEnabled(true);
        jTextFieldKuerzel.setText("");
        jTextFieldPmNr.setText("");
        jTextFieldTischNr.setText("");
        jTextFieldKuerzel.requestFocus();
    }//GEN-LAST:event_jButtonNeuActionPerformed

    private void jButtonTestkonsolenausgabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestkonsolenausgabeActionPerformed
        // TODO add your handling code here:
        List<Material> material = null;
        try {
            material = materialDAO.getAllMaterial();
        } catch (SQLException ex) {
            Logger.getLogger(Trace.class.getName()).log(Level.SEVERE, null, ex);
        }
        /**
        for (Material t : material) {
            System.out.println(t);
        }
        */
        
        MaterialTableModel model;
        model = new MaterialTableModel(material);
        table.setModel(model);
        
    }//GEN-LAST:event_jButtonTestkonsolenausgabeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNeu;
    private javax.swing.JButton jButtonTestkonsolenausgabe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTischNr;
    private javax.swing.JScrollPane jScrollPaneMaterial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCharge;
    private javax.swing.JTextField jTextFieldKuerzel;
    private javax.swing.JTextField jTextFieldPmNr;
    private javax.swing.JTextField jTextFieldSeriennummer;
    private javax.swing.JTextField jTextFieldTischNr;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
