package traceability;

import DAO.MaterialDAO;
import daten.Material;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static traceability.TraceStart.stammdaten;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author U14
 */
public class TraceSmdRuesten extends javax.swing.JFrame {
    
    private MaterialDAO materialDAO;
    private MaterialDAO insertMaterialDAO;
    
    private JTable table;

    /**
     * Creates new form Trace
     */
    public TraceSmdRuesten() {
        initComponents();
        
          try {
            materialDAO = new MaterialDAO();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(TraceSmdRuesten.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCharge = new javax.swing.JTextField();
        jTextFieldSeriennummer = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPmNr = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label4 = new java.awt.Label();
        jButtonNeu = new javax.swing.JButton();
        jScrollPaneMaterial = new javax.swing.JScrollPane();
        jLabelTischNr = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jTextFieldMaschine = new javax.swing.JTextField();

        setTitle("Tracebility THT Material");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 10));
        setResizable(false);

        jTextFieldCharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChargeActionPerformed(evt);
            }
        });

        jTextFieldSeriennummer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSeriennummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeriennummerActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Seriennummer:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SMD Material rüsten");

        jTextFieldPmNr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldPmNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPmNrActionPerformed(evt);
            }
        });

        jSeparator2.setName("TracebilityThtMaterial"); // NOI18N

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Charge:");

        jButtonNeu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNeu.setText("Neuer Betribsauftrag");
        jButtonNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeuActionPerformed(evt);
            }
        });

        jLabelTischNr.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("Arbeitsplatz (Maschine):");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Betriebsauftrag:");

        jTextFieldMaschine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldMaschine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaschineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneMaterial)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNeu)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(240, 240, 240)
                .addComponent(jLabelTischNr)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPmNr, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jTextFieldSeriennummer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaschine, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTischNr)
                            .addComponent(jLabel1))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPmNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldMaschine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSeriennummer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNeu)
                .addContainerGap())
        );

        table = new JTable();
        jScrollPaneMaterial.setViewportView(table);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChargeActionPerformed
        // TODO add your handling code here:
        //System.out.println("Charge:  " + jTextFieldCharge.getText());
        //charge.setText("");
        jTextFieldSeriennummer.requestFocus();
    }//GEN-LAST:event_jTextFieldChargeActionPerformed

    private void jTextFieldSeriennummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeriennummerActionPerformed
        // TODO add your handling code here:

        //System.out.println("Kuezel: " + jTextFieldKuerzel.getText() + " PmNr: " + jTextFieldPmNr.getText() + " Tisch: " + jTextFieldTischNr.getText() + " Charge: " + jTextFieldCharge.getText() + 
         //                   " Seriennummer: " + jTextFieldSeriennummer.getText());
        
        Material tempMaterial = null;
     
        String Kuerzel = stammdaten.getUser(); 
        String artikelnr = jTextFieldSeriennummer.getText();
        String dieAbteilung = stammdaten.getAbteilung();
        String ArbPlatz = stammdaten.getArbeitsplatz();
        String TischNr = stammdaten.getArbeitsplatz();
        String PmNr = jTextFieldPmNr.getText();
        String Charge = jTextFieldCharge.getText();
        String rollew = "0";
        String datum = "0";
        
        tempMaterial = new Material (datum, Kuerzel, artikelnr, dieAbteilung, ArbPlatz,  PmNr, Charge, rollew);
        
        materialDAO.insertMaterial(tempMaterial);
        
        jTextFieldSeriennummer.setText("");
        jTextFieldCharge.setText("");
        jTextFieldCharge.requestFocus();
        
              List<Material> material = null;
        try {
            material = materialDAO.getAllMaterial();
        } catch (SQLException ex) {
            Logger.getLogger(TraceSmdRuesten.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MaterialTableModel model;
        model = new MaterialTableModel(material);
        table.setModel(model);
        
        // Tabelle nach der 2. Spalte sortiet
        table.setAutoCreateRowSorter(true);
        table.getRowSorter().toggleSortOrder(1);
        table.getRowSorter().toggleSortOrder(1);
        
    }//GEN-LAST:event_jTextFieldSeriennummerActionPerformed

    private void jTextFieldPmNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPmNrActionPerformed
        // TODO add your handling code here:
        //jTextFieldPmNr.setEnabled(false);
        //labelBetriebsauftrag.setBounds(10, 100, 100, 10);
        jTextFieldPmNr.setEditable(false);
        jTextFieldMaschine.requestFocus();
        //labelBetriebsauftrag.setVisible(true);
        //labelBetriebsauftrag.setText(jTextFieldPmNr.getText());
    }//GEN-LAST:event_jTextFieldPmNrActionPerformed

    private void jButtonNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeuActionPerformed
        // TODO add your handling code here:
        jTextFieldPmNr.setEnabled(true);
        jTextFieldPmNr.setText("");
        jTextFieldPmNr.setVisible(true);
        jTextFieldPmNr.requestFocus();
    }//GEN-LAST:event_jButtonNeuActionPerformed

    private void jTextFieldMaschineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaschineActionPerformed
        // TODO add your handling code here:
        jTextFieldMaschine.setEditable(false);
        jTextFieldCharge.requestFocus();
    }//GEN-LAST:event_jTextFieldMaschineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraceSmdRuesten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraceSmdRuesten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraceSmdRuesten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraceSmdRuesten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraceSmdRuesten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNeu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTischNr;
    private javax.swing.JScrollPane jScrollPaneMaterial;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCharge;
    private javax.swing.JTextField jTextFieldMaschine;
    private javax.swing.JTextField jTextFieldPmNr;
    private javax.swing.JTextField jTextFieldSeriennummer;
    private java.awt.Label label1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
