package traceability;

import DAO.ReparaturDAO;
import daten.Reparatur;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static traceability.TraceStart.stammdaten;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ralf Hackmann
 */
public class TraceReparatur extends javax.swing.JFrame {
    
    
    private ReparaturDAO insertReparaturDAO;
    private JTable table;


    
   

    /**
     * Creates new form Trace
     */
    public TraceReparatur() {
        initComponents();
        
          try {
            insertReparaturDAO = new ReparaturDAO();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(TraceReparatur.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCharge = new javax.swing.JTextField();
        jTextFieldSeriennummer = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBetriebsauftrag = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        jButtonNeuerBetriebsauftrag = new javax.swing.JButton();
        jLabelTischNr = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        jTextFieldArtikelnummer = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        jTextFieldPosition = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        jButtonNeu1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneBemerkung = new javax.swing.JTextPane();
        jScrollPaneReparatur = new javax.swing.JScrollPane();

        setTitle("Tracebility THT Material");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 10));
        setResizable(false);

        jTextFieldCharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChargeActionPerformed(evt);
            }
        });

        jTextFieldSeriennummer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSeriennummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeriennummerActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Seriennummer:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reparatur");

        jTextFieldBetriebsauftrag.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldBetriebsauftrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBetriebsauftragActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Charge:");

        jButtonNeuerBetriebsauftrag.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNeuerBetriebsauftrag.setText("Neuer Betribsauftrag");
        jButtonNeuerBetriebsauftrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeuerBetriebsauftragActionPerformed(evt);
            }
        });

        jLabelTischNr.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Betriebsauftrag:");

        jTextFieldArtikelnummer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldArtikelnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldArtikelnummerActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("Artikelnummer:");

        jTextFieldPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPositionActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setText("Position:");

        label9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label9.setText("Bemerkung:");

        jButtonNeu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNeu1.setText("SPEICHERN");
        jButtonNeu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeu1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPaneBemerkung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260)
                        .addComponent(jLabelTischNr)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNeuerBetriebsauftrag)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNeu1)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneReparatur, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jTextFieldSeriennummer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBetriebsauftrag, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldArtikelnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTischNr)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBetriebsauftrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeriennummer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArtikelnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNeuerBetriebsauftrag)
                    .addComponent(jButtonNeu1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneReparatur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        table = new JTable();
        jScrollPaneReparatur.setViewportView(table);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChargeActionPerformed
        // TODO add your handling code here:
        //jTextFieldCharge.setEditable(false);
        jTextFieldArtikelnummer.requestFocus();
    }//GEN-LAST:event_jTextFieldChargeActionPerformed

    private void jTextFieldSeriennummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeriennummerActionPerformed
        // TODO add your handling code here:
        //jTextFieldSeriennummer.setEditable(false);
        jTextFieldCharge.requestFocus();
      
    }//GEN-LAST:event_jTextFieldSeriennummerActionPerformed

    private void jTextFieldBetriebsauftragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBetriebsauftragActionPerformed
        // TODO add your handling code here:
        jTextFieldBetriebsauftrag.setEditable(false);
        jTextFieldSeriennummer.requestFocus();
 
    }//GEN-LAST:event_jTextFieldBetriebsauftragActionPerformed

    private void jButtonNeuerBetriebsauftragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeuerBetriebsauftragActionPerformed
        // TODO add your handling code here:
        jTextFieldBetriebsauftrag.setEnabled(true);
        jTextFieldBetriebsauftrag.setText("");
        jTextFieldBetriebsauftrag.setVisible(true);
        jTextFieldBetriebsauftrag.setEditable(true);
        jTextFieldBetriebsauftrag.requestFocus();
    }//GEN-LAST:event_jButtonNeuerBetriebsauftragActionPerformed

    private void jTextFieldArtikelnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldArtikelnummerActionPerformed
        // TODO add your handling code here:
        //jTextFieldArtikelnummer.setEditable(false);
        jTextFieldPosition.requestFocus();
    }//GEN-LAST:event_jTextFieldArtikelnummerActionPerformed

    private void jTextFieldPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionActionPerformed
        // TODO add your handling code here:
        //jTextFieldPosition.setEditable(false);
        jTextPaneBemerkung.requestFocus();
    }//GEN-LAST:event_jTextFieldPositionActionPerformed

    private void jButtonNeu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeu1ActionPerformed
        // TODO add your handling code here:
        speichern();
        laden(Integer.parseInt(jTextFieldBetriebsauftrag.getText()));
        jTextFieldArtikelnummer.setText("");
        jTextFieldSeriennummer.setText("");
        jTextFieldCharge.setText("");
        jTextFieldPosition.setText("");
        jTextPaneBemerkung.setText("");
        jTextFieldSeriennummer.requestFocus();
        
        
      
    }//GEN-LAST:event_jButtonNeu1ActionPerformed

    
    private void speichern() {
        
        Reparatur tempReparatur = null;
     
        String Kuerzel = stammdaten.getUser(); 
        Integer betriebsauftrag = Integer.parseInt(jTextFieldBetriebsauftrag.getText());
        Integer seriennr = Integer.parseInt(jTextFieldSeriennummer.getText());
        String position = jTextFieldPosition.getText();
        String artikelnr = jTextFieldArtikelnummer.getText();
        String chargenr = jTextFieldCharge.getText();
        String bemerkung = jTextPaneBemerkung.getText();
        String datum = "0";
        
        tempReparatur = new Reparatur (Kuerzel, betriebsauftrag, seriennr, position, artikelnr, chargenr, bemerkung, datum );
        
        insertReparaturDAO.insertReparatur(tempReparatur);
        
    }
    
    private void laden( Integer betriebsauftrag) {
        
           List<Reparatur> reparatur = null;
           ReparaturDAO reparaturDAO = null;
        try {
            reparaturDAO = new ReparaturDAO();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(TraceReparatur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            reparatur = reparaturDAO.getReparatur(betriebsauftrag.toString()); 
        } catch (SQLException ex) {
            Logger.getLogger(TraceThtMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ReparaturTableModel model;
        model = new ReparaturTableModel(reparatur);
        table.setModel(model);
        
        // Tabelle nach der 2. Spalte sortiet
        table.setAutoCreateRowSorter(true);
        table.getRowSorter().toggleSortOrder(1);
        table.getRowSorter().toggleSortOrder(1);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraceReparatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraceReparatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraceReparatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraceReparatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraceReparatur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNeu1;
    private javax.swing.JButton jButtonNeuerBetriebsauftrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTischNr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneReparatur;
    private javax.swing.JTextField jTextFieldArtikelnummer;
    private javax.swing.JTextField jTextFieldBetriebsauftrag;
    private javax.swing.JTextField jTextFieldCharge;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldSeriennummer;
    private javax.swing.JTextPane jTextPaneBemerkung;
    private java.awt.Label label1;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
